### ISSUE TITLE
Merge section 6.2 and 6.4

### ISSUE THREAD

**Issue by gselander** [core-wg/oscore-groupcomm#105]
From Section 13.12 :
"As discussed in [Section 6.2](https://core-wg.github.io/oscore-groupcomm/draft-ietf-core-oscore-groupcomm.html#sec-synch-seq-num), a Replay Window may be initialized as not valid "

Section 6.2 is essentially one paragraph long and, does not discuss the above. It can be merged with 6.4 which is also about replay protection. The reference in 13.12 also needs to be fixed.

**Comment by chrysn** [comment]
Is there any difference between the SSN being out of sync and the replay window being initialized as not valid?

**Comment by gselander** [comment]
Good question, which text are you reading? Perhaps we wouldn't use the term "initialized as not valid" for SSN being out of sync, but they can both serve as examples of how a replay window became invalid.

**Comment by chrysn** [comment]
The place I've seen "not synchronized or the RW is invalid" is in the
commit that fixed this issue (hence replying here).

I think the expression "not having / knowing a valid Replay Window" is
the most descriptive, as SSN "synchronization" to me reads like there is
a tighter coupling than there actually is.

So maybe

-A server may not be synchronized[...]
+A server may not have a valid Replay Window (typically stemming from
loss of mutable security context in any form of
{{ssec-loss-mutable-context}}).
