### ISSUE TITLE
Recude the size of responses with 64 bytes

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscore-groupcomm#13]
In Group OSCORE with ECDSA and EdDSA signatures, I think the overhead of responses can be cut with a whopping 64 bytes (for 256 bit curves), by removing the signature and calculating the AEAD with an ephemeral-static ECHD key instead of the server's sender key. An ECDSA signature is (r, s) where r = g^x can be seen as an ephemeral Diffie-Hellman public key. 

Current specification:
```
Client					Server
----------------------------------------------
Sender Key				Receiver Key
Reciever Key				Sender Key
Private Sig Key				Public Sig Key
Public Sig Key				Private Sig Key

--------------->
AEAD( client sender key, ... ), (r1 = g^x, s1)
<---------------
AEAD( server sender key, ... ), (r2 = g^y, s2)
```

Optimized solution to reduce message size of repsonses:
```
Client					Server
----------------------------------------------
Sender Key				Receiver Key
Private Sig Key				Public Sig Key
Public DH Key (g^v)			Private SH Key (v)

--------------->
AEAD( client sender key, ... ), (r1 = g^x, s1)
<---------------
AEAD( g^xv, ... )


```
Pros:

- 	Cuts a whopping 64 bytes from responses
- 	g^xv can be calculated while waiting for the repsonse
- 	In deployments with fixed roles the number of asymmetric keys stay the same	

Cons:

- 	In mesh networks the number of asymmetric keys doubles
- 	Signature checking intermediaries is not supported.

This idea seems to work for both ECDSA, deterministic ECDSA and EdDSA. For deterministic algorithms it works as the signed message is never the same due to the inclusion of a sequence number. In the case of EdDSA the client and server has to transform the point in Edwards form to Montgomery form to use the standardized X25519.

(This comment was updated with information on EdDSA and deterministic signatures after suggestions from Erik Thormarker).

**Comment by emanjon** [comment]
The amount of reduction depends on the number of nodes in the system:

- 2 nodes   41% reduction in OSCORE overhead (number of bytes)
- 10 nodes  75% reduction in OSCORE overhead (number of bytes)
- 100 nodes 82% reduction in OSCORE overhead (number of bytes)

Such a significant reduction would be very lucrative, especially in mesh networks where the number of key in symmetric solutions grow as n^2. Group OSCORE could e.g. specify two different modes, one that support signature verifying middle-boxes and one modes that does not.

**Comment by marco-tiloca-sics** [comment]
Now covered by the optimized mode.
