### ISSUE TITLE
Concerns with EC key joint signature and DH usage

### ISSUE THREAD

**Issue by gselander** [core-wg/oscore-groupcomm#73]
Provide better justification for the security of the use of the same public key in pairwise and group modes.

https://mailarchive.ietf.org/arch/msg/core/ujj_I-LlqW9fq__quh-YqKS0fF0/

**Comment by marco-tiloca-sics** [comment]
Addressed in https://github.com/core-wg/oscore-groupcomm/commit/1fe710c720aab07b50af876d17e9fa72a55efc18 and https://github.com/core-wg/oscore-groupcomm/commit/92122dc8952d364f69f99b490f7afd5d1d20753f

**Comment by marco-tiloca-sics** [comment]
This was addressed in v -12 through the commits above, building on [1] and adapting the derivation of pairwise keys accordingly. Follow-up of issue #72.

[1] https://eprint.iacr.org/2021/509
