### ISSUE TITLE
Align with draft-ietf-cose-countersign security considerations

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscore-groupcomm#78]
"When either COSE_Encrypt and COSE_Mac is used and more than two parties share the key, data origin authentication is not provided. Any party that knows the message-authentication key can compute a valid authentication tag; therefore, the contents could originate from any one of the parties that share the key.

Countersignatures of COSE_Encrypt and COSE_Mac with short authentication tags do not provide the security properties associated with the same algorithm used in COSE_Sign. To provide 128-bit security against collision attacks, the tag length MUST be at least 256-bits. A countersignature of a COSE_Mac with AES-MAC 256/128 provides at most 64 bits of integrity protection. Similarly, a countersignature of a COSE_Encrypt with AES-CCM-16-64-128 provides at most 32 bits bits of integrity protection."

**Comment by marco-tiloca-sics** [comment]
Addressed in https://github.com/core-wg/oscore-groupcomm/commit/f3d028120357e9ca4bff427793947dd267e7a453
