### ISSUE TITLE
Gateway applications with Group OSCORE 

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscore-groupcomm#8]
This use cases seem to have been forgotten. It is not mentioned in the Group OSCORE document, and I do not think there was any discussion ending in that the use case should not be supported.

Use case description from Jim Schaad:

> 
> I have a room full of light bulbs and switches which constitute a multicast group.  For various reasons these devices do not both doing any signature checking.  There are some additional controllers that live outside of the subnet which consists of the room which need to be able to control the devices and query the state of various devices in the that subsystem.  
>     
> There lives a firewall/gateway on the border between the subsystem and the entire network that wants to prevent unauthenticated commands coming in from the outside or information which is not authenticated leaking out from the inside.  The first way to do this is to make the firewall/gateway be a traffic re-writing system.  That means that it will receive commands from the outside, authenticate them, translate them to a command the will work inside of the room and sends it.  It will then deal with the responses and translate them back to a format that the original device would understand and authenticate.
>     
> The second way is to say that the firewall/gateway is not a trusted party to this situation.  However, there is a desire to drastically cut down the attack space that is coming from the outside world into the room.  In this case when the gateway receives a request, it validates the signature on the group message and ensures that it is signed by a member of the group.  It does this by checking the counter signature on the message, but does not try and decrypt the message.  At that point it lets the message into the room where it will be acted on by the local devices.  It would also be possible that the responses would be signed by the firewall/gateway rather than each individual device providing a signature.  
>     
>  For the second method, any data which is not determinable by the firewall without being a member of the group with the exception of the signing key, is going to be a problem as the signature cannot validated.

**Comment by emanjon** [comment]
I think both of these use cases are interesting and definitely worth discussing. The first use case seems quite straightforward to achieve and likely worth making sure it works with Group OSCORE. The firewall still need to be able to fetch information from somewhere, but does not need to be trusted. The second use case is more complicated as the firewall need to be semi-trusted, and there the construction also changes the meaning of the Sender ID as it is now the firewall that has signed rather than the original sender.

**Comment by fpalombini** [comment]
John I think you reversed first and second use case in your second comment, correct? 

I think the second case (where the gateway only verifies the signatures) is a very valid use case of group OSCORE and should be described (possibly in appendix). The first case, on the contrary, is not necessarily a group OSCORE case. There could be a group OSCORE between the gateway and the firewall/gateway, but that is not fundamental to the scenario: here the middle node is trusted on one side by the external controller, on the other side by the multicast group. He could be considered the endpoint for those communications.

So I suggest we only describe the second case.
