### ISSUE TITLE
Group OSCORE is not secure with the future planned encryption algorithms for the AEAD interface

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscore-groupcomm#82]
COSE has discussed and are are planning to standardize new encryption algorithms for the AEAD interface after a request from FIDO. The new algorithms would not provide any integrity protection.

The current version of the Group OSCORE draft would not be secure at all with these new algorithms due to the unusual design choice to let the sender countersign it's own AEAD. This could easily be addressed by using a traditional MAC-then-Sign approach.

**Comment by marco-tiloca-sics** [comment]
See https://github.com/core-wg/oscore-groupcomm/commit/e4b076223354f0904ebbaa370a7d69e1a59ebd55

As discussed, now a recipient endpoint owning the latest group keying material does not store the public keys of sender endpoints that are not current group members. This builds on the Group Manager informing of former group members when rekeying the group.

As a result, proof of group-membership is always achieved, also for messages protected in group mode when using an encryption algorithm that does not provide integrity protection (i.e., there is no tag providing group authentication).
