### ISSUE TITLE
Counter Signature Parameters are not signature parameters.

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscore-groupcomm#84]
The Counter Signature Parameters are not signature parameters following JOSE, COSE, X.509 terminology. They are part of the public key. The correct thing here is likely to do is to include the public key structure (maybe a CWT, X509, C509) in the external_aad.

**Comment by marco-tiloca-sics** [comment]
Addressed in https://github.com/core-wg/oscore-groupcomm/commit/481188b671ecd49dc4b0c6fc082dd1d09b68556e
