### ISSUE TITLE
Deployments using pairwise only should not be forced to implement signatures.

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscore-groupcomm#88]
Pairwise a very important and useful piece of Group OSCORE. As already stated "A special deployment of Group OSCORE is to use pairwise mode only". This make very much sense to have duch deployments. Such deployments should definitly not be forced to implement signatures.

**Comment by marco-tiloca-sics** [comment]
Addressed in https://github.com/core-wg/oscore-groupcomm/commit/7a80990154dc7927a9803a6d9e38143cff21dcf1
