### ISSUE TITLE
Key formats, Public key algorithms, and integrity protectioin.

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscore-groupcomm#89]
The draft does not dicuss key formats at all. Typical formats to use would be CWT, X509 and C509. The draft needs to discuss this at least shortly. 

The public key credential includes the public key algorithm, something that the draft calls signature algorithms.

The public key credential should be included in the external_aad, COSE does not do this automatically for you.

**Comment by marco-tiloca-sics** [comment]
Addressed in https://github.com/core-wg/oscore-groupcomm/commit/b7b044555f43763e0e32d5fcd2312a4032843420   and   https://github.com/core-wg/oscore-groupcomm/commit/481188b671ecd49dc4b0c6fc082dd1d09b68556e
