### ISSUE TITLE
Secret Derivation Algorithm

### ISSUE THREAD

**Issue by emanjon** [core-wg/oscore-groupcomm#90]
The name is a bit strange. According to COSE this is a Key Agreement Algorithm. I suggest changing to "Pairwise Key Agreement Algorithm".

If the signature algorithms is protected in the external_aad, this algorithm should as well.

The key derivation in the Key Agreeent algorithm may not be HKDF. The key derivation included in the key agreement algorithm is used to derive the shared secret, it should not be used to derive the sender keys. The RFC 8613 HKDF Algorithm should be used in the derivation below.

Pairwise Sender Key    = HKDF(Sender Key, Shared Secret, info, L)

**Comment by marco-tiloca-sics** [comment]
Addressed in https://github.com/core-wg/oscore-groupcomm/commit/b7b044555f43763e0e32d5fcd2312a4032843420   and   https://github.com/core-wg/oscore-groupcomm/commit/481188b671ecd49dc4b0c6fc082dd1d09b68556e
